### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by 89z** [richardartoul/molecule#10]
The v2 package is here:

~~~
google.golang.org/protobuf
~~~

and the v1 package is here:

~~~
github.com/golang/protobuf
~~~

I notice that the v1 package is still being used:

https://github.com/richardartoul/molecule/blob/e3f68f39eab407e4cb098eccbde62fa4312121ca/go.mod#L5-L9

are any plans to change to v2?

**Comment by richardartoul** [comment]
@89z is this impacting your dependencies? As far as I remember this library is supposed to be zero "real" dependencies and those things are only used in my tests where I don't think upgrading would be that important.

Is this impacting your project somehow?

**Comment by 89z** [comment]
oh sorry, you are right
