### ISSUE TITLE
Parse unknown message 

### ISSUE THREAD

**Issue by 89z** [richardartoul/molecule#11]
Is it possible to do something like this? For example, with this input:

~~~
\x12\x02\b\x01
~~~

return something simlar to this:

~~~
Message{
   Tag{2,Bytes},
   LengthPrefix{
      Tag{1,Varint},Uvarint(1)
   }
}
~~~

**Comment by richardartoul** [comment]
@89z I don't totally understand, what are you trying to do that the library interfaces don't support?

**Comment by 89z** [comment]
Given some arbitrary Protocol Buffer input bytes, I would like to parse that into a `map` or `struct`.

**Comment by 89z** [comment]
As a workaround, I wrote my own:

https://github.com/89z/parse/tree/master/protobuf

**Comment by richardartoul** [comment]
ok im gonna mark this as resolved since you seem to have solved your issue

**Comment by 89z** [comment]
Just because I implemented this, doesnt mean that Molecule couldnt implement this as well...

**Comment by richardartoul** [comment]
@89z I'm pretty sure you can do what you want using this API: https://pkg.go.dev/github.com/richardartoul/molecule#MessageEach

**Comment by 89z** [comment]
I finally tried your suggestion, but it doesnt seem possible to handle embedded messages. I have an example below. You could but a `NewBuffer` call inside the function, but messages can have any level of nesting.

~~~go
package main

import (
   "fmt"
   "github.com/richardartoul/molecule"
   "github.com/richardartoul/molecule/src/codec"
   "os"
)

func main() {
   buf, err := os.ReadFile("details.txt")
   if err != nil {
      panic(err)
   }
   buffer := codec.NewBuffer(buf)
   molecule.MessageEach(buffer, func(n int32, v molecule.Value) (bool, error) {
      if len(v.Bytes) > 9 {
         v.Bytes = v.Bytes[:9]
      }
      fmt.Println(n, v.WireType, v.Number, v.Bytes)
      return true, nil
   })
}
~~~
